# Generated by Django 4.1.3 on 2022-11-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refId', models.IntegerField()),
                ('name', models.TextField()),
                ('contact', models.IntegerField(max_length=10)),
                ('seatRow', models.CharField(max_length=1)),
                ('seatNum', models.IntegerField()),
            ],
        ),
    ]
