# Generated by Django 4.1.3 on 2022-11-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticket_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
