# Generated by Django 4.1.3 on 2022-12-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_alter_ticket_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seatNum',
            field=models.TextField(default=''),
        ),
    ]
